# This workflow will build and push a Docker image to Docker Hub
# For more information see: https://github.com/marketplace/actions/build-and-push-docker-images

name: Publish Docker Image

on:
  # run when a PR is closed
  #   The current design was implemented with the expectation that all
  #   proper releases will be created in release branches, and that all
  #   feature branches will be merged into the release branch (NOT into main).
  #   When the release branch is ready to actually be released, it is merged
  #   into main, at which point this workflow will generate the corresponding
  #   release image for Docker Hub.
  pull_request:
    branches: [ "main" ]
    types:    [ "closed" ]

permissions:
  contents: read

jobs:
  docker:
    # only run if the PR closed after merging
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    
    # needed to access the file with our version info
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Get version
      id: vars
      run: echo "semver=$(cat version.txt)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.2.0
      with:
        push: true
        # This uses the version we loaded from a file earlier
        tags: ${{ steps.vars.outputs.semver }}
        #labels: ${{ steps.nametag.outputs.labels }}
        
