# This workflow will build and push a Docker image when a PR is closed after merging
# For more information see: https://github.com/marketplace/actions/build-and-push-docker-images

name: Python application

on:
  pull_request:
    branches: [ "main" ]
    types:    [ "closed" ]

permissions:
  contents: read

jobs:
  docker:
    # only run if the PR closed after merging
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:    
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.2.0
      with:
        push: true
        tags: user/app:latest
