# This manually activated workflow doesn't achieve any output beyond testing 
name: Test Docker Format

on: workflow_dispatch
    
permissions:
  contents: read

jobs:
  test-Docker-Format:
    runs-on: ubuntu-latest

    steps:

    - name: Get version
      id: vars
      run: echo "semver=$(cat version.txt)" >> $GITHUB_OUTPUT

    - name: Test version
      run: echo ${{ steps.vars.outputs.semver }}


    - name: Set up name and tag
      id:   nametag
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/calc
        # generate Docker tags based on the following events/attributes
        tags: |
          type=semver,pattern={{version}}


    # Print my output to the log     
    - name: Print the output
      run: |
        echo ${{ steps.nametag.outputs.tags }}
        echo ${{ steps.nametag.outputs.labels }}
